[2025-03-27T15:19:45.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T15:19:45.398+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.fifth_task scheduled__2025-03-26T00:00:00+00:00 [queued]>
[2025-03-27T15:19:45.413+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.fifth_task scheduled__2025-03-26T00:00:00+00:00 [queued]>
[2025-03-27T15:19:45.414+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T15:19:45.430+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fifth_task> on 2025-03-26 00:00:00+00:00
[2025-03-27T15:19:45.437+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T15:19:45.438+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-03-27T15:19:45.439+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'fifth_task', 'scheduled__2025-03-26T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpqpc0ehuv']
[2025-03-27T15:19:45.440+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask fifth_task
[2025-03-27T15:19:45.489+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.fifth_task scheduled__2025-03-26T00:00:00+00:00 [running]> on host 2a584310a0bb
[2025-03-27T15:19:45.575+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='fifth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-26T00:00:00+00:00'
[2025-03-27T15:19:45.576+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T15:19:45.593+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-27T15:19:45.595+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my fifth task']
[2025-03-27T15:19:45.610+0000] {subprocess.py:99} INFO - Output:
[2025-03-27T15:19:45.612+0000] {subprocess.py:106} INFO - hello world, this is my fifth task
[2025-03-27T15:19:45.612+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-27T15:19:45.638+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T15:19:45.638+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fifth_task, run_id=scheduled__2025-03-26T00:00:00+00:00, execution_date=20250326T000000, start_date=20250327T151945, end_date=20250327T151945
[2025-03-27T15:19:45.695+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T15:19:45.720+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-27T15:19:45.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
