[2025-03-27T15:19:46.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T15:19:46.765+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.sixth_task scheduled__2025-03-26T00:00:00+00:00 [queued]>
[2025-03-27T15:19:46.776+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.sixth_task scheduled__2025-03-26T00:00:00+00:00 [queued]>
[2025-03-27T15:19:46.776+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T15:19:46.794+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): sixth_task> on 2025-03-26 00:00:00+00:00
[2025-03-27T15:19:46.802+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T15:19:46.803+0000] {standard_task_runner.py:72} INFO - Started process 113 to run task
[2025-03-27T15:19:46.803+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'sixth_task', 'scheduled__2025-03-26T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp27qbpz46']
[2025-03-27T15:19:46.804+0000] {standard_task_runner.py:105} INFO - Job 108: Subtask sixth_task
[2025-03-27T15:19:46.870+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.sixth_task scheduled__2025-03-26T00:00:00+00:00 [running]> on host 2a584310a0bb
[2025-03-27T15:19:46.946+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='sixth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-26T00:00:00+00:00'
[2025-03-27T15:19:46.947+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T15:19:46.960+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-27T15:19:46.961+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my sixth task']
[2025-03-27T15:19:46.970+0000] {subprocess.py:99} INFO - Output:
[2025-03-27T15:19:46.971+0000] {subprocess.py:106} INFO - hello world, this is my sixth task
[2025-03-27T15:19:46.972+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-27T15:19:46.994+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T15:19:46.995+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=sixth_task, run_id=scheduled__2025-03-26T00:00:00+00:00, execution_date=20250326T000000, start_date=20250327T151946, end_date=20250327T151946
[2025-03-27T15:19:47.062+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T15:19:47.104+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T15:19:47.109+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
