[2025-03-24T13:21:36.797+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T13:21:36.886+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-24T13:21:36.915+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-24T13:21:36.916+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T13:21:36.973+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-21 00:00:00+00:00
[2025-03-24T13:21:36.992+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=394) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T13:21:36.998+0000] {standard_task_runner.py:72} INFO - Started process 401 to run task
[2025-03-24T13:21:37.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpvoi_xblj']
[2025-03-24T13:21:37.012+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask second_task
[2025-03-24T13:21:37.186+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-03-21T00:00:00+00:00 [running]> on host e1537a8d388b
[2025-03-24T13:21:37.664+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-24T13:21:37.679+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T13:21:37.751+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T13:21:37.771+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my second task']
[2025-03-24T13:21:37.859+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T13:21:37.867+0000] {subprocess.py:106} INFO - hello world, this is my second task
[2025-03-24T13:21:37.869+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T13:21:38.006+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T13:21:38.008+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250324T132136, end_date=20250324T132138
[2025-03-24T13:21:38.160+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T13:21:38.269+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T13:21:38.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
