[2025-04-02T11:48:52.384+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T11:48:52.403+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.fifth_task scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-02T11:48:52.412+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.fifth_task scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-02T11:48:52.413+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-02T11:48:52.426+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fifth_task> on 2025-04-01 00:00:00+00:00
[2025-04-02T11:48:52.439+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-02T11:48:52.441+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-04-02T11:48:52.442+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'fifth_task', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpewvthkc1']
[2025-04-02T11:48:52.443+0000] {standard_task_runner.py:105} INFO - Job 196: Subtask fifth_task
[2025-04-02T11:48:52.485+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.fifth_task scheduled__2025-04-01T00:00:00+00:00 [running]> on host d7b554d6843c
[2025-04-02T11:48:52.567+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='fifth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-02T11:48:52.568+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T11:48:52.581+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-02T11:48:52.583+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my fifth task']
[2025-04-02T11:48:52.593+0000] {subprocess.py:99} INFO - Output:
[2025-04-02T11:48:52.595+0000] {subprocess.py:106} INFO - hello world, this is my fifth task
[2025-04-02T11:48:52.596+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-02T11:48:52.620+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T11:48:52.621+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fifth_task, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250402T114852, end_date=20250402T114852
[2025-04-02T11:48:52.779+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-02T11:48:52.804+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T11:48:52.851+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
