[2025-03-24T13:21:36.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T13:21:36.911+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-03-18T00:00:00+00:00 [queued]>
[2025-03-24T13:21:36.953+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-03-18T00:00:00+00:00 [queued]>
[2025-03-24T13:21:36.955+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T13:21:36.998+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-18 00:00:00+00:00
[2025-03-24T13:21:37.016+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=395) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T13:21:37.019+0000] {standard_task_runner.py:72} INFO - Started process 404 to run task
[2025-03-24T13:21:37.022+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-03-18T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp4hyn_nws']
[2025-03-24T13:21:37.027+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask second_task
[2025-03-24T13:21:37.242+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-03-18T00:00:00+00:00 [running]> on host e1537a8d388b
[2025-03-24T13:21:37.688+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T00:00:00+00:00'
[2025-03-24T13:21:37.691+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T13:21:37.750+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T13:21:37.765+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my second task']
[2025-03-24T13:21:37.805+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T13:21:37.852+0000] {subprocess.py:106} INFO - hello world, this is my second task
[2025-03-24T13:21:37.853+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T13:21:37.989+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T13:21:37.991+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-03-18T00:00:00+00:00, execution_date=20250318T000000, start_date=20250324T132136, end_date=20250324T132137
[2025-03-24T13:21:38.151+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T13:21:38.277+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T13:21:38.287+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
