[2025-03-24T13:21:36.803+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T13:21:36.893+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-03-19T00:00:00+00:00 [queued]>
[2025-03-24T13:21:36.920+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-03-19T00:00:00+00:00 [queued]>
[2025-03-24T13:21:36.921+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T13:21:36.987+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-19 00:00:00+00:00
[2025-03-24T13:21:37.024+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=399) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T13:21:37.031+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-03-19T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpc3iq0w1p']
[2025-03-24T13:21:37.032+0000] {standard_task_runner.py:72} INFO - Started process 406 to run task
[2025-03-24T13:21:37.033+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask second_task
[2025-03-24T13:21:37.199+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-03-19T00:00:00+00:00 [running]> on host e1537a8d388b
[2025-03-24T13:21:37.781+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T00:00:00+00:00'
[2025-03-24T13:21:37.786+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T13:21:37.878+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T13:21:37.906+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my second task']
[2025-03-24T13:21:37.991+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T13:21:38.004+0000] {subprocess.py:106} INFO - hello world, this is my second task
[2025-03-24T13:21:38.006+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T13:21:38.119+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T13:21:38.121+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-03-19T00:00:00+00:00, execution_date=20250319T000000, start_date=20250324T132136, end_date=20250324T132138
[2025-03-24T13:21:38.276+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T13:21:38.376+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T13:21:38.387+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
